@HostAddress = https://localhost:53405/api
@DatabaseAddress = {{HostAddress}}/database

GET {{DatabaseAddress}}/databasename

###

GET {{DatabaseAddress}}/tables

###

GET {{DatabaseAddress}}/tables/11

###

GET {{DatabaseAddress}}/views

###

GET {{DatabaseAddress}}/views/12

###
